Feature/tcp pathfinder
sonia-auv/provider_dvl pull request #15
Opened 2022-02-04 13:18 UTC by supertoto29

**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
This has been the code ran during the quebec competition and we should just put the branch in develop as a backup. Master can be done when the code for AUV7 is taken.

## How has this been tested ?
Tested at the quebec competition

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2022-02-04 13:24 UTC, supertoto29 commented
@Kam0ss  @alexemdesgagne Since the purpose of this pull request is to make a backup can we merge even if the action aren't passing? The branch feature/noetic should fix everything

2022-02-04 14:10 UTC, alexemdesgagne approved these changes
Lgtm !

2022-02-04 14:29 UTC, Kam0ss requested changes
Is this no going to erase the code for AUV7 ?

2022-02-04 14:29 UTC, Kam0ss commented on .github/workflows/docker-image-perception-feature.yml
> -          docker push ${GITHUB_REMOTE_URL}/${IMAGE_NAME}:${ARCH}-${TARGET_TYPE}-${TARGET_VERSION}-${GITHUB_REF##*/}
I think we should keep this as we have seen on other repos this can be a problem when working on multiple fixes/features

2022-02-04 14:29 UTC, Kam0ss commented on .github/workflows/docker-image-perception-feature.yml
> -          docker push ${GITHUB_REMOTE_URL}/${IMAGE_NAME}:${ARCH}-${TARGET_TYPE}-${TARGET_VERSION}-${GITHUB_REF##*/}
I think we should keep this as we have seen on other repos this can be a problem when working on multiple fixes/features

2022-02-06 20:39 UTC, Kam0ss approved these changes
LGTM

2022-02-06 20:40 UTC, merged